### ISSUE TITLE
Github no longer accepts access token in query param

### ISSUE THREAD

**Issue by greysilly7** [packwiz/packwiz-installer#49] opened 2023-01-01 05:32 UTC
"Must specify access token via Authorization header. https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param" is what happenes

**Comment by comp500** [comment] 2023-01-02 21:41
Duplicate of https://github.com/packwiz/packwiz-installer-bootstrap/issues/3 (I'm planning to move to my own Maven repository, so an access token shouldn't be necessary fairly soon)

**Closed by comp500** 2023-01-02 21:41 UTC
