### ISSUE TITLE
java.lang.IllegalArgumentException: Illegal character in path at index 11: BiblioCraft[v2.4.5][MC1.12.2].jar

### ISSUE THREAD

**Issue by greysilly7** [packwiz/packwiz-installer#35] opened 2022-06-29 02:32 UTC
I tried the current workaround and removing mode and adding the actual URL to download but it didn't work
```
name = "BiblioCraft"
filename = "BiblioCraft-v2.4.6-MC1.12.2.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "6eb72c2a6b9d202e53e760e26048c230cd2ca5da"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3647708
project-id = 228027
```

**Comment by comp500** [comment] 2022-06-29 02:34
Duplicate of #5 - I'm working on this issue, the proper fix is very nearly completed.

**Closed by comp500** 2022-06-29 02:34 UTC
